### PR TITLE
Add dummy processes

### PR DESCRIPTION
**Pull request by olejandro**
as if they were read from the excel files

### CODE REVIEW

**Comment by olejandro** [comment]
@samwebster @siddharth-krishna could you review this?
+8% on demo 1

**Comment by siddharth-krishna** [comment]
@olejandro this looks good, thanks! I'm only wondering if the set of default dummy processes is fixed for all models? Or would it make more sense to move it from the code to a meta text file like `mappings.txt` or maybe an auxiliary input json?

**Review by samwebster — APPROVED** [review]

**Comment by olejandro** [comment]
Thanks @siddharth-krishna ! 😊 yes, I think it would be good to have those in some kind of a meta / settings file. It might be a bit too early to design it though, because I expect a number of such quick fixes. 😊 Maybe we could already open an issue with the current candidates to be included in such a file(s)?

**Comment by siddharth-krishna** [comment]
Sounds good!

**Review by siddharth-krishna — APPROVED** [review]

**Pull request merged**
