### PR TITLE
Reduce repetitive calculations in extract_commodity_groups

### PR DESCRIPTION
**Pull request by olejandro**

### CODE REVIEW

**Comment by olejandro** [comment]
CI did not run automatically, so ran it manually: https://github.com/samwebster/times-excel-reader/actions/runs/4319357578/jobs/7538444636

**Review by siddharth-krishna — APPROVED** [review]
Nice, the new code also looks cleaner and is easier to understand!

@samwebster  any idea why CI isn't running? (I don't think we're out of minutes, as it's still running on the "Update TODOs PR".) It's a required status, so we'd need it to run in order to merge this in.

**Comment by olejandro** [comment]
I'll add another commit with comments to trigger it. Probably GitHub had some service disruption yesterday...

**Comment by siddharth-krishna** [comment]
Ah I had added a merge commit just to check the same thing. Looks like it worked now :)

**Pull request merged**
